### ISSUE TITLE
Pipeline: Success message although Stardog refuses graph

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#276]
If data is in wrong format, f.ex. if the value **1.1** is mapped as `int`, the pipeline displays success but no data is available in preview

- Sample project: https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!zmoke-test-issue-276-m3q433r6ye0/metadata
- Sample data: [AllDataTypes.zip](https://github.com/zazuko/cube-creator/files/5641857/AllDataTypes.zip) (map column "Float" to data type "int" in order to reproduce)

**Comment by l00mi** [comment]
depends on https://github.com/zazuko/barnard59-graph-store/issues/7

**Comment by l00mi** [comment]
Fixed with https://github.com/zazuko/barnard59-core/pull/58

**Comment by FabianCretton** [comment]
Today I gave a try to see if the user is now informed when Stardog refuses a graph.
I did launch a transformation of Daniels' project:
https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!case-study-wrong-data-type-nbqjgalry8q/csv-mapping

The transformation fails, the icons becomes red, BUT I don't see any message or any explanation for the user.
Is it planned to improve this ?
Let say I have a 50'000 lines CSV, with one little data type error in one cell, how do I deal with that ? Could I have an "error at line 256" ? Or at least have a clue about the problem ?

**Comment by tpluscode** [comment]
Yes, next deployment will include an improvement for this (#561)

**Comment by l00mi** [comment]
@FabianCretton apart from this fix to hint that the error comes from a wrong datatype mentioned by @tpluscode (partly covering https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/194 which is in the Backlog) further Data Validation efforts need to be postponed to the next project. They are clearly in Backlog: e.g. https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/197 https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/195

**Comment by FabianCretton** [comment]
I did rerun "Case Study Wrong Data Type" this morning, GUI version 0.1.21, and still not any error message to the user.

**Comment by l00mi** [comment]
As discussed, there will be no error message to the end-user as this is part of https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/197
