### ISSUE TITLE
Cannot save cube metadata

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#852]
Error:
```
Resource https://register.ld.admin.ch/opendataswiss/org/schweizerisches-bundesarchiv-bar not found
```

https://sentry.zazuko.com/organizations/zazuko/issues/1007/

Originally reported by Véronique.

**Comment by tpluscode** [comment]
@martinmaillard this is not caused by the DNS change but rather by #806 

The update code tries to load the `dcterms:creator` organisation from cube creator database but we are in fact fetching them from Lindas. Hence, it's a `register.ld.admin.ch` resource

**Comment by l00mi** [comment]
@tpluscode easy fix?

**Comment by tpluscode** [comment]
Maybe

The list of organisations is quite long. We use them to find their `dcat:accessURL` and `void:sparqlEndpoint` but those values are only in our internal "Organisation Profile" right now.

I would propose that we start linking our profiles with the `register.ld` identifier and use that link to look up the URLs we need. For example the above could be

```turtle
<organization/sfa>
  dcat:accessURL <https://culture.ld.admin.ch/query> ;
  void:sparqlEndpoint <https://culture.ld.admin.ch/sparql> ;
  skos:exactMatch <https://register.ld.admin.ch/opendataswiss/org/schweizerisches-bundesarchiv-bar> .
```

So the lookup in Cube Creator would become

```SPARQL
select ?orgProfile {
  graph ?orgProfile {
    ?orgProfile skos:exactMatch <https://register.ld.admin.ch/opendataswiss/org/schweizerisches-bundesarchiv-bar>
  }
}
```

**Comment by l00mi** [comment]
Why would we need to couple one with the other?

**Comment by martinmaillard** [comment]
I think the problem is a misunderstanding on my end when I implemented #806. If we use `maintainer` instead of `dcterms:creator` to get the organization id it should work no?

**Comment by tpluscode** [comment]
> Why would we need to couple one with the other?

Aren't they effectively different representations of same entities?

> If we use `maintainer` instead of `dcterms:creator` to get the organization id it should work no?

It begs additional questions

1. Is the metadata property `dcterms:creator` even needed if we already choose the maintainer ini project settings?
2. Having both, would it ever make sense to select a different organization for the project and different for the dataset metadata?

**Comment by PDumasBAR** [comment]
Hard to test the DCat harvester with this bug.
I need to publish some cubes from sfa and/or foen to have something to export :). There is only one published cube of foen on int, zero in test. Can you solve the problem ?
All the fields are also duplicated in this formular (https://github.com/zazuko/cube-creator/issues/855 is not solved)
